version: 0.2
phases:
install:
commands:
- echo install step...
pre_build:
commands:
- echo logging in to AWS ECR...
- $(aws ecr get-login --no-include-email --region us-east-1)
build:
commands:
- echo build Docker image on `date`
- cd src
- docker build -t capstoners_image:latest
- docker tag capstoners_image:latest 962804699607.dkr.ecr.us-west-2.amazonaws.com/capstoners:latest #
post_build:
commands:
- echo build Docker image complete `date`
- echo push latest Dockear images to ECR...
- docker push 962804699607.dkr.ecr.us-west-2.amazonaws.com/capstoners:latest